### ISSUE TITLE
如何取消Archive subtitles

### ISSUE THREAD

**Issue by senchuanqianxia** [wayneclub/Subtitle-Downloader#64]
![image](https://github.com/wayneclub/Subtitle-Downloader/assets/151311089/efdee165-a1e6-4208-a994-f8674ad182d7)
怎麼關閉Archive subtitles

**Comment by wayneclub** [comment]
> ![image](https://user-images.githubusercontent.com/151311089/283972253-efdee165-a1e6-4208-a994-f8674ad182d7.png) 怎麼關閉Archive subtitles

已新增關閉打包壓縮功能，在 `user_config.toml` 設定 `archive = false`

```toml
[subtitles]
default-language = 'zh-Hant' # all/en/zh-Hant/zh-Hans/zh-HK
default-format = '.srt'      # .srt/.ass
archive = true               # true/false
```
