### ISSUE TITLE
Some tags are loss when converting vtt to srt or ass.

### ISSUE THREAD

**Issue by vleaf0210** [wayneclub/Subtitle-Downloader#68]
After downloading subtitles from this tool, some tags are lost in the process of converting the format.
So could you please add vtt to the default format option so that we can skip the conversion?

**Comment by Ninelpienel** [comment]
Yeah, I have the same problem. The an8 tag is missing.

**Comment by wayneclub** [comment]
> After downloading subtitles from this tool, some tags are lost in the process of converting the format. So could you please add vtt to the default format option so that we can skip the conversion?

Add .vtt format. Set in `user-config.toml`

```toml
[subtitles]
default-language = 'all' # all/en/zh-Hant/zh-Hans/zh-HK/ja/ko
default-format = '.vtt'  # .srt/.ass/.vtt
archive = true           # true/false
fix-subtitle = false      # true/false
```
